### ISSUE TITLE
Pulling records using lexicon should ensure trailing dot

### ISSUE THREAD

**Issue by brianeclow** [doddo/octodns-lexicon#3]
Using the `godaddy` provider:
```
octodns.record.ValidationError: Invalid record @.example.com.
  - NS value "ns93.domaincontrol.com" missing trailing .
  - NS value "ns94.domaincontrol.com" missing trailing .
```
The Rackspace provider for octoDNS had a similar problem, due to how the provider stores the entries. The [defs](https://github.com/github/octodns/blob/master/octodns/provider/rackspace.py#L20-L29) were added.

However, this might not be ideal for all providers. 😞

**Comment by doddo** [comment]
Indeed, there are some inconsistencies between Lexicon providers, but It should be a simple enough fix, I think. If one can reasonably assume that `"ns94.domaincontrol.com"` should be treated as FQDN and not a relative entry.

**Comment by doddo** [comment]
@brianeclow could you try and see if this fixes the issue you are facing?

**Comment by doddo** [comment]
Root cause seems to be in the godaddy provider: https://github.com/AnalogJ/lexicon/issues/518

**Comment by brianeclow** [comment]
Let me pull and test. But in light of the lexicon issue, it might be a problem. I will also update the pinned version to the one indicated in their issue.

**Comment by brianeclow** [comment]
That combination has gotten me to the next issue. Which I think resides with how, um, relaxed godaddy is with enforcing the RFCs for DNS. 🤦

**Comment by doddo** [comment]
Is that related to that default forward record or suchlike which godaddy populates new zones with. -- there's a `lenient` boolean option you can set on the provider and it's not gonna crash on invalid records 👍

**Comment by brianeclow** [comment]
I've hit it on two things: the "forward" record as A Record, and their laziness on MX records.

How do you add `lenient` to this provider? I am not finding much documentation on where/how to add it.

**Comment by brianeclow** [comment]
I used my existing configuration, but did a dump passing in the `--lenient` flag. It still barfs on the MX records. Someone isn't playing nice.

**Comment by doddo** [comment]
yes I saw that and can confirm that Godaddy lexicon provider does not handle MX records extra fields very good unfortunatly.
